# Generated by Django 4.0.3 on 2022-07-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hiredat',
            new_name='hiredate',
        ),
    ]
